spring:
  application:
    name: spring-boot-admin-server
  boot:
    admin:
      ui:
        title: Eazyschool Admin Server

server:
  port: 9000

management:
  endpoints:
    web:
      exposure:
        include: '*'